### ISSUE TITLE
Leaks memory with every request

### ISSUE THREAD

**Issue by terrisgit** [moonthug/hapi-xray#1]
Using 
nodejs 8.9.0 (carbon) - nodejs 10 seemed to be worse, actually
hapi-xray 1.0.11 
hapi 18.3.1
aws-sdk 2.455.0
aws-xray-sdk 2.3.3
and no other plugins...

If you hit a simple GET endpoint (for example returns 200 and does nothing else) using one request at a time (no concurrency), RAM used by the nodejs process trends forever upwards. Removing the endpoint causes the leak to disappear.

The plugin is added via a "server.js" type file:

```
const AWSXRay = require('aws-xray-sdk');
...
    {
      plugin: require('hapi-xray'),
      options: {
        captureAWS: true,
        plugins: [AWSXRay.plugins.ECSPlugin],
        segmentName: 'test',
      },
    },
```

**Comment by moonthug** [comment]
It seems that http segments weren't being closed properly. I've ran a few tests on `clinic.js` and all seems ok.

Please can you update to `1.1.0` and confirm this issue is resolved?

**Comment by moonthug** [comment]
I have disabled automatic mode. Hopefully the new `async_hooks` version of xray-sdk makes it more usable with Hapi.

As a result of switching to manual mode, the current `segment` is now available on the request.

Please upgrade to `1.1.1`
