### ISSUE TITLE
Issue with casing of headers

### ISSUE THREAD

**Issue by eric-swann-q2** [moonthug/hapi-xray#16]
I noticed that one of the tests was failing and that one of my changes had been reverted, which was causing the test failure.  It's this line:
```
const segment = new AWSXray.Segment(name, header.Root, header.Parent);
```

Following what was done in the express middleware, I had changed it to:
```
const segment = new AWSXray.Segment(name, header.root, header.parent);
```
The test stub sets up the headers expecting them to be lowercase.

I know that node typically lowercases headers:
https://github.com/nodejs/node-v0.x-archive/issues/1954

Was this causing an issue for you in your testing with the segment not getting set properly? 

Would it make sense to do the following in case they do come in lowercased?
```
const segment = new AWSXray.Segment(name, header.Root || header.root, 
header.Parent || header.parent);
```

**Comment by moonthug** [comment]
This is a weird one. In my testing, this was causing an issue, having got the result of the header in a down stream service resembling the following. However the express example seems to suggest otherwise.

```
{
  "Root": "1-5ec40b48-a592b45a8149ed2c393487c4",
  "Parent": "8dc7444e7b4a7b9c",
  "Sampled": "1"
}
```

I'm happy to go with your suggestion. I'll get it updated and published on 3.0.2.

🍻

**Comment by moonthug** [comment]
Seems to be related to how the xray-patched version of http puts values into the Xray headers.

https://github.com/aws/aws-xray-sdk-node/blob/master/packages/core/lib/patchers/http_p.js#L124

**Comment by eric-swann-q2** [comment]
OK cool
